services:
  ba-assemble-nemplads-to-sql:
    container_name: ba-assemble-nemplads-to-sql
    # image: 'ghcr.io/hjk-automatisering/ba-assemble-nemplads-to-sql:main' # Uncomment on portainer
    build: . # Remove on portainer
    volumes:
      - filer-assemble-nemplads:/shr/AssembleNemplads
    env_file:
      - .env # stack.env on portainer
    environment:
      - TZ=Europe/Copenhagen
    labels:
      ofelia.enabled: "true"
      ofelia.job-run.ba-assemble-nemplads-to-sql.schedule: "${CRON_SCHEDULE}"
      ofelia.job-run.ba-assemble-nemplads-to-sql.container: "ba-assemble-nemplads-to-sql"

  ofelia:
    image: mcuadros/ofelia:latest
    container_name: ofelia
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - ba-assemble-nemplads-to-sql

volumes:
  filer-assemble-nemplads:
    external: true