services:
  ba-assemble-nemplads-to-sql-worker:
    container_name: ba-assemble-nemplads-to-sql-worker
    # image: 'ghcr.io/hjk-automatisering/ba-assemble-nemplads-to-sql:main' # Uncomment on portainer
    build: . # Remove on portainer
    command: sleep infinity
    restart: always
    volumes:
      - filer-assemble-nemplads:/shr/AssembleNemplads
    env_file:
      - .env # stack.env on portainer
    environment:
      - TZ=Europe/Copenhagen
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.ba-assemble-nemplads-to-sql-worker.schedule: "${CRON_SCHEDULE}"
      ofelia.job-exec.ba-assemble-nemplads-to-sql-worker.container: "ba-assemble-nemplads-to-sql-worker"
      ofelia.job-exec.ba-assemble-nemplads-to-sql-worker.command: "python main.py"

  ba-assemble-nemplads-to-sql-scheduler:
    image: mcuadros/ofelia:latest
    container_name: ba-assemble-nemplads-to-sql-scheduler
    restart: always
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - ba-assemble-nemplads-to-sql-worker

volumes:
  filer-assemble-nemplads:
    external: true